name: Cl By Miraç
on:
  workflow_dispatch:
    inputs:
      NGROK_AUTH_TOKEN:
        description: 'CRD Kodunuzu Giriniz'
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: İndiriliyor
      run: Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
    - name: Dosya Çıkartılıyor
      run: Expand-Archive ngrok.zip
    - name: Hesaba Giriliyor
    #ngrok config add-authtoken 2Zdr9J5XYvQU3MqPKmmIDNzTA2J_2iDCGVHmTvzEHVM8oaAG9
      run: .\ngrok\ngrok.exe config add-authtoken $Env:NGROK_AUTH_TOKEN
    - name: Enable TS
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
    - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - run: Set-LocalUser -Name "Miraç" -Password (ConvertTo-SecureString -AsPlainText "Test123." -Force)
    - name: Create Tunnel
      run: .\ngrok\ngrok.exe tcp 3389
