name: Cl By Miraç
on:
  workflow_dispatch:
    inputs:
      NGROK_AUTH_TOKEN:
        description: 'Ngrok Auth Tokeninizi Girin'
      Password:
        description: 'Windows Şifrenizi girin'
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: İndiriliyor
      run: Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
    - name: Dosya Çıkartılıyor
      run: Expand-Archive ngrok.zip
    - name: Hesaba Giriliyor
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
       NGROK_AUTH_TOKEN: ${{ github.event.inputs.NGROK_AUTH_TOKEN }}
    - name: Enable TS
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
    - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - run: Set-LocalUser -Name "runneradmin"
    - run: Set-LocalUser -Password (ConvertTo-SecureString -AsPlainText $Env:Password -Force)
      env:
         Password: ${{ github.event.inputs.Password }}
      
    - name: Create Tunnel
      run: .\ngrok\ngrok.exe tcp 3389
