name: Cl By Miraç
on:
  workflow_dispatch:
    inputs:
      NGROK_AUTH_TOKEN:
        description: 'Ngrok Auth Tokeninizi Girin'
        required: true
      Password:
        description: 'Windows Şifrenizi girin'
        required: true
jobs:
  Kurulum:
    runs-on: windows-latest
    steps:
    - name: İndiriliyor
      run: Invoke-WebRequest https://s2.dosya.tc/en2.php?a=server30/1wertc/winrar-x64-701.zip&b=42bf3554017066cc5d7c5a8d098e0d7d&c=1718731240
    - name: Dosya Çıkartılıyor
      run: Expand-Archive winrar-x64-701.zip
    - name: İndiriliyor (1)
      run: Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip
    - name: Dosya Çıkartılıyor (1)
      run: Expand-Archive ngrok.zip
    - name: Hesaba Giriliyor
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
       NGROK_AUTH_TOKEN: ${{ github.event.inputs.NGROK_AUTH_TOKEN }}
    - name: Kurulum Yapılıyor
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
    - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText $Env:Password -Force)
      env:
         Password: ${{ github.event.inputs.Password }}
    - name: Tünel Oluşturuluyor
      run: .\ngrok\ngrok.exe tcp 3389


      #Tüm haklar Miracyusuf1620 ye aittir çalmayınız çalanlara itibar etmeyiniz
      
